### ISSUE TITLE
App Container Crashes, Only Database Container is Running – Improved Documentation Needed

### ISSUE THREAD

**Issue by montespertoli-paktribune** [ubicloud/ubicloud#2575]
## Problem Description:
I tried to get the Control Panel app up and running, but the app container keeps crashing on my system. Only the database container stays up. Here are the steps I’ve followed so far:

1. I followed the installation instructions from the README.
2. The database container starts and works fine.
3. The app container starts but crashes shortly after.

## Logs:
[_ubicloud-app_logs.txt](https://github.com/user-attachments/files/18378815/_ubicloud-app_logs.txt)

**Comment by ChristianSchneeweiss** [comment]
I have the same error. Would love to get some feedback

**Comment by devops-cybersapient** [comment]
same error here. any fixes?

**Comment by enescakir** [comment]
Hi @montespertoli-paktribune, @ChristianSchneeweiss, @devops-cybersapient, sorry for any inconvenience.

The issue is that the demo instructions on the README runs in development mode, while our Docker image only contains production gem packages. I've created a PR to resolve this: https://github.com/ubicloud/ubicloud/pull/2586. Once this PR is merged, we'll publish a new Docker image which should resolve your issue.

If you'd prefer to use Ubicloud services without self-hosting, you're welcome to try our managed services at https://console.ubicloud.com

**Comment by enescakir** [comment]
We published a new image. Can you pull the latest image and try it again?

**Comment by logixmlbesy** [comment]
> We published a new image. Can you pull the latest image and try it again?

Worked straight away. Thank you so much! 🙏

**Comment by devops-cybersapient** [comment]
@enescakir the db migrator is still not coming up




root@bm-m1-gra11:/home/ubuntu/ubicloud# docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS                     PORTS                                       NAMES
a4de89e8bbfb   ubicloud/ubicloud:latest   "foreman start"          3 minutes ago   Up 3 minutes               0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   ubicloud-app
d96dba170932   ubicloud/ubicloud:latest   "bundle exec rake de…"   3 minutes ago   Exited (0) 3 minutes ago                                               ubicloud-db-migrator
e3d104b49799   postgres:15.4              "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes (healthy)     0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   ubicloud-postgres






Logs


oot@bm-m1-gra11:/home/ubuntu/ubicloud# docker logs d96dba170932
/usr/local/bundle/gems/sequel-5.88.0/lib/sequel/extensions/schema_caching.rb:76: warning: Could not load OIDs for the following custom types: allocation_state, arch, ha_type, hostname_version, lb_algorithm, lb_hc_protocol, lb_node_state, lb_stack, page_severity, postgres_flavor, postgres_version, project_reputation, synchronization_status, timeline_access, vm_display_state
E, [2025-01-15T04:36:25.287724 #1] ERROR -- : PG::UndefinedTable: ERROR:  relation "schema_migrations" does not exist
LINE 1: SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
                                  ^: SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
I, [2025-01-15T04:36:25.290139 #1]  INFO -- : (0.002135s) CREATE TABLE "schema_migrations" ("filename" text PRIMARY KEY)
E, [2025-01-15T04:36:25.290379 #1] ERROR -- : PG::UndefinedTable: ERROR:  relation "schema_info" does not exist
LINE 1: SELECT NULL AS "nil" FROM "schema_info" LIMIT 1
                                  ^: SELECT NULL AS "nil" FROM "schema_info" LIMIT 1
I, [2025-01-15T04:36:25.290776 #1]  INFO -- : (0.000239s) SELECT "filename" FROM "schema_migrations" ORDER BY "filename"
I, [2025-01-15T04:36:25.381417 #1]  INFO -- : Begin applying migration 20230117_tables.rb, direction: up
I, [2025-01-15T04:36:25.381589 #1]  INFO -- : (0.000120s) BEGIN
I, [2025-01-15T04:36:25.381950 #1]  INFO -- : (0.000296s) CREATE TYPE "allocation_state" AS ENUM ('unprepared', 'accepting', 'draining')
I, [2025-01-15T04:36:25.382190 #1]  INFO -- : (0.000149s) SELECT CAST("enumtypid" AS integer) AS "v", "enumlabel" FROM "pg_enum" ORDER BY "enumtypid", "enumsortorder"
I, [2025-01-15T04:36:25.382607 #1]  INFO -- : (0.000264s) SELECT "typname", CAST("typarray" AS integer) AS "v" FROM "pg_type" WHERE (("oid" IN ($1::int4)) AND ("typarray" != $2::int4)); [17150, 0]
I, [2025-01-15T04:36:25.382881 #1]  INFO -- : (0.000181s) SELECT "typarray", "oid" FROM "pg_type" WHERE ("typname" = $1) LIMIT 1; ["allocation_state"]
I, [2025-01-15T04:36:25.385108 #1]  INFO -- : (0.002047s) CREATE TABLE "strand" ("id" uuid DEFAULT gen_random_uuid() P
